name: Branch Integration

on:
  push:
    branches:
      - main # 변경 사항을 통합할 대상 브랜치
jobs:
  integrate_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Merge Branch
        run: |
          git config user.name "KwonBoWon"
          git config user.email "bogod1207@naver.com"
          git checkout main
          git merge ${{ github.ref }}

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main # 변경 사항을 푸시할 대상 브랜치
