name: README-Update
on:
    push:
      paths:
        - 'README.md'
jobs:
  update_docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Update documentation
        run: |
          echo "Documentation update" >> README.md
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update documentation
          commit_options: '--no-verify'
          commit_user_name: GitHub Actions
          commit_user_email: actions@github.com
          branch: ${{ github.ref }}
